#PBS -S /bin/bash
#PBS -l nodes=1:ppn=1
#PBS -l mem=25g
#PBS -l walltime=04:55:00

###############################
# Move to execution directory #
###############################
cd $PBS_O_WORKDIR

################################
# source environment variables #
################################
source environment_variables.sh

#######
# Run #
#######
ls ${SJ_TAB_DIR}/*SJ.out.tab.gz > $SJ_TAB_FILE_LIST

bin/rnastar_sjtab_merge.py --mincount 10 $FASTA_FAI  $SJ_TAB_FILE_LIST > $NEW_SJ_TABS
