---
title: "Only 0m sample Log R Ratio"
author: "Eli"
date: "April 03, 2019"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r libraries}
library( here )
library( tidyverse )
library( DESeq2 )
```

```{r setup_parallel_execution}
RUN_IN_PARALLEL = TRUE
PARALLEL_THREADS = 10

# ATTN VERY IMPORTANT WARNING
# I was running this either on Windows 10
# or Linux. If you're using something else
# you will likely need to either change
# this logic or disable parallel
# operation.

if ( RUN_IN_PARALLEL & .Platform$OS.type == "windows" ) {
  library( doSNOW )
  local_cluster <- makeCluster( PARALLEL_THREADS )
  registerDoSNOW( local_cluster )
} else if ( RUN_IN_PARALLEL & .Platform$OS.type == "unix" ) {
  library( doMC )
  registerDoMC( PARALLEL_THREADS )
}
```

```{r source_shared}
source( here::here( 'src', 'shared_project_functions.R' ) )
```

```{r rgsm}
rgsm <- read_csv( file = here::here( 'data', 'ssc_rnaseq_readgroup_info.csv' ) ) %>%
  select( .data = ., RGSM, Individual, Status, GenStatus, Tissue, Cohort, Machine, Cycles, Timepoint ) %>%
  mutate( .data = ., filter_criteria = case_when(
    GenStatus == "Control" ~ 'keep',
    GenStatus == "SSc" & Timepoint == '0m' ~ 'keep',
    TRUE ~ 'drop'
  )) %>%
  filter( .data = ., filter_criteria == 'keep' ) %>%
  as.data.frame( . ) %>%
  unique( . )

rgsm_list <- rgsm %>%
  pull( RGSM ) %>%
  sort( . ) %>%
  unique( . )
```

## genes
```{r design}
design_tbl <- rgsm %>%
  select( .data = ., RGSM, Status, Machine ) %>%
  as.data.frame( . )
rownames( design_tbl ) = design_tbl$RGSM 
```

```{r read_gene_counts_genes}
gene_counts <- read_tsv( file = here::here( 'results', 'gene_featurecounts.tsv.gz' ), col_types = cols( .default = col_integer(), gene_id = col_character() ) ) %>%
  as.data.frame( . ) %>%
  column_to_rownames( "gene_id" ) %>%
  as.matrix( . )

gene_counts <- gene_counts[ which( rowSums( gene_counts ) > 5 ), ]

both_ids <- intersect( rownames( design_tbl ), colnames( gene_counts ) )
design_tbl <- design_tbl[ both_ids, ]
gene_counts <- gene_counts[ ,both_ids ]
```

```{r load_into_deseq2_genes}
deseqObj <- DESeqDataSetFromMatrix( countData = gene_counts, colData = design_tbl, design = ~ Machine + Status )

deseqObj <- DESeq( deseqObj, test = "Wald", betaPrior = FALSE, parallel = RUN_IN_PARALLEL )
```

```{r extracting_logrratio_genes}
assay( rlog( deseqObj, blind=FALSE ) ) %>%
  as.data.frame( . ) %>%
  rownames_to_column( "gene_id" ) %>%
  write_csv( x = ., path =  here::here( 'results', 'gene_0m_sample_rlog.csv.gz' ) ) 
```

## SAF
```{r read_gene_counts_unspliced}
gene_counts <- read_tsv( file = here::here( 'results', 'unspliced_featurecounts.tsv.gz' ), col_types = cols( .default = col_integer(), gene_id = col_character() ) ) %>%
  as.data.frame( . ) %>%
  column_to_rownames( "gene_id" ) %>%
  as.matrix( . )

gene_counts <- gene_counts[ which( rowSums( gene_counts ) > 5 ), ]

both_ids <- intersect( rownames( design_tbl ), colnames( gene_counts ) )
design_tbl <- design_tbl[ both_ids, ]
gene_counts <- gene_counts[ ,both_ids ]
```

```{r load_into_deseq2_unspliced}
deseqObj <- DESeqDataSetFromMatrix( countData = gene_counts, colData = design_tbl, design = ~ Machine + Status )

deseqObj <- DESeq( deseqObj, test = "Wald", betaPrior = FALSE, parallel = RUN_IN_PARALLEL )
```

```{r extracting_logrratio_unspliced}
assay( rlog( deseqObj, blind=FALSE ) ) %>%
  as.data.frame( . ) %>%
  rownames_to_column( "gene_id" ) %>%
  	write_csv( x = ., path =  here::here( 'results', 'unspliced_0m_sample_rlog.csv.gz' ) ) 
```

```{r cleanup_parallel_executuion}
if ( RUN_IN_PARALLEL & .Platform$OS.type == "windows" ) {
  stopCluster( local_cluster )
} 
```

# Session info
```{r versions}
Sys.time()

getwd()
  
sessionInfo()
```
